CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260719155632_InitialPostgreSQL') THEN
    CREATE TABLE "Clientes" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Nombre" text NOT NULL,
        "Numero" text NOT NULL,
        "Email" text NOT NULL,
        "Contraseña" text NOT NULL,
        "Estado" text NOT NULL,
        CONSTRAINT "PK_Clientes" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260719155632_InitialPostgreSQL') THEN
    CREATE TABLE "Productos" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Nombre" text NOT NULL,
        "Descripcion" text NOT NULL,
        "Stock" integer NOT NULL,
        "Precio" numeric NOT NULL,
        "Estado" text NOT NULL,
        CONSTRAINT "PK_Productos" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260719155632_InitialPostgreSQL') THEN
    CREATE TABLE "Rols" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Descripcion" text NOT NULL,
        "Estado" text NOT NULL,
        CONSTRAINT "PK_Rols" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260719155632_InitialPostgreSQL') THEN
    CREATE TABLE "Usuarios" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Nombre" text NOT NULL,
        "Numero" text NOT NULL,
        "Email" text NOT NULL,
        "Contraseña" text NOT NULL,
        "Estado" text NOT NULL,
        CONSTRAINT "PK_Usuarios" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260719155632_InitialPostgreSQL') THEN
    CREATE TABLE "Sucursales" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Id_cliente" integer NOT NULL,
        "Nombre" text NOT NULL,
        "Descripcion" text NOT NULL,
        "Ubicacion" text NOT NULL,
        "Estado" text NOT NULL,
        CONSTRAINT "PK_Sucursales" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Sucursales_Clientes_Id_cliente" FOREIGN KEY ("Id_cliente") REFERENCES "Clientes" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260719155632_InitialPostgreSQL') THEN
    CREATE TABLE "Usuario_Rols" (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        id_rol integer NOT NULL,
        id_usuario integer NOT NULL,
        "Estado" text NOT NULL,
        CONSTRAINT "PK_Usuario_Rols" PRIMARY KEY (id),
        CONSTRAINT "FK_Usuario_Rols_Rols_id_rol" FOREIGN KEY (id_rol) REFERENCES "Rols" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Usuario_Rols_Usuarios_id_usuario" FOREIGN KEY (id_usuario) REFERENCES "Usuarios" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260719155632_InitialPostgreSQL') THEN
    CREATE INDEX "IX_Sucursales_Id_cliente" ON "Sucursales" ("Id_cliente");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260719155632_InitialPostgreSQL') THEN
    CREATE INDEX "IX_Usuario_Rols_id_rol" ON "Usuario_Rols" (id_rol);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260719155632_InitialPostgreSQL') THEN
    CREATE INDEX "IX_Usuario_Rols_id_usuario" ON "Usuario_Rols" (id_usuario);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260719155632_InitialPostgreSQL') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260719155632_InitialPostgreSQL', '9.0.18');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260729232240_migrationsv3') THEN
    CREATE TABLE "Pedidos" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Id_sucursal" integer NOT NULL,
        "Id_cliente" integer NOT NULL,
        "Fecha" timestamp with time zone NOT NULL,
        "Observacion" text NOT NULL,
        "Total" numeric NOT NULL,
        "Estado" text NOT NULL,
        CONSTRAINT "PK_Pedidos" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Pedidos_Clientes_Id_cliente" FOREIGN KEY ("Id_cliente") REFERENCES "Clientes" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Pedidos_Sucursales_Id_sucursal" FOREIGN KEY ("Id_sucursal") REFERENCES "Sucursales" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260729232240_migrationsv3') THEN
    CREATE TABLE "Detalle_Pedidos" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Id_pedido" integer NOT NULL,
        "Id_producto" integer NOT NULL,
        "Cantidad" integer NOT NULL,
        "Subtotal" numeric NOT NULL,
        "Estado" text NOT NULL,
        CONSTRAINT "PK_Detalle_Pedidos" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Detalle_Pedidos_Pedidos_Id_pedido" FOREIGN KEY ("Id_pedido") REFERENCES "Pedidos" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Detalle_Pedidos_Productos_Id_producto" FOREIGN KEY ("Id_producto") REFERENCES "Productos" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260729232240_migrationsv3') THEN
    CREATE INDEX "IX_Detalle_Pedidos_Id_pedido" ON "Detalle_Pedidos" ("Id_pedido");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260729232240_migrationsv3') THEN
    CREATE INDEX "IX_Detalle_Pedidos_Id_producto" ON "Detalle_Pedidos" ("Id_producto");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260729232240_migrationsv3') THEN
    CREATE INDEX "IX_Pedidos_Id_cliente" ON "Pedidos" ("Id_cliente");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260729232240_migrationsv3') THEN
    CREATE INDEX "IX_Pedidos_Id_sucursal" ON "Pedidos" ("Id_sucursal");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260729232240_migrationsv3') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260729232240_migrationsv3', '9.0.18');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260729235302_migrationsv31') THEN
    ALTER TABLE "Pedidos" ALTER COLUMN "Observacion" DROP NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260729235302_migrationsv31') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260729235302_migrationsv31', '9.0.18');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260730002301_migrationsv32') THEN
    CREATE TABLE "Tipo_Pagos" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Descripcion" text NOT NULL,
        "Estado" text NOT NULL,
        CONSTRAINT "PK_Tipo_Pagos" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260730002301_migrationsv32') THEN
    CREATE TABLE "Pagos" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Id_usuario" integer NOT NULL,
        "Id_pedido" integer NOT NULL,
        "Id_tipoPago" integer NOT NULL,
        "Fecha" timestamp with time zone NOT NULL,
        "MontoPagado" numeric NOT NULL,
        "SaldoPendiente" text NOT NULL,
        "Estado" text NOT NULL,
        CONSTRAINT "PK_Pagos" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Pagos_Pedidos_Id_pedido" FOREIGN KEY ("Id_pedido") REFERENCES "Pedidos" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Pagos_Tipo_Pagos_Id_tipoPago" FOREIGN KEY ("Id_tipoPago") REFERENCES "Tipo_Pagos" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Pagos_Usuarios_Id_usuario" FOREIGN KEY ("Id_usuario") REFERENCES "Usuarios" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260730002301_migrationsv32') THEN
    CREATE INDEX "IX_Pagos_Id_pedido" ON "Pagos" ("Id_pedido");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260730002301_migrationsv32') THEN
    CREATE INDEX "IX_Pagos_Id_tipoPago" ON "Pagos" ("Id_tipoPago");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260730002301_migrationsv32') THEN
    CREATE INDEX "IX_Pagos_Id_usuario" ON "Pagos" ("Id_usuario");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260730002301_migrationsv32') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260730002301_migrationsv32', '9.0.18');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260730004107_migrationsv33') THEN
    ALTER TABLE "Pagos"
    ALTER COLUMN "SaldoPendiente"
    TYPE numeric(10,2)
    USING (
        CASE
            WHEN "SaldoPendiente" IS NULL
                 OR BTRIM("SaldoPendiente") = ''
                THEN 0.00

            WHEN REPLACE(
                    BTRIM("SaldoPendiente"),
                    ',',
                    '.'
                 )
                 ~ '^[+-]?[0-9]+([.][0-9]+)?$'
                THEN REPLACE(
                    BTRIM("SaldoPendiente"),
                    ',',
                    '.'
                )::numeric(10,2)

            ELSE 0.00
        END
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260730004107_migrationsv33') THEN
    ALTER TABLE "Pagos" ALTER COLUMN "MontoPagado" TYPE numeric(10,2);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260730004107_migrationsv33') THEN
    ALTER TABLE "Pagos" ALTER COLUMN "Estado" TYPE character varying(30);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260730004107_migrationsv33') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260730004107_migrationsv33', '9.0.18');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260803224443_migrations23') THEN
    CREATE TABLE "Vehiculos" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Marca" text NOT NULL,
        "Placa" text,
        "Cantidad_Carga" text NOT NULL,
        "Estado" text NOT NULL,
        CONSTRAINT "PK_Vehiculos" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260803224443_migrations23') THEN
    CREATE TABLE "Asignacion_Vehiculos" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        id_usuario integer NOT NULL,
        id_vehiculo integer NOT NULL,
        "Fecha" timestamp with time zone NOT NULL,
        "Estado" text NOT NULL,
        CONSTRAINT "PK_Asignacion_Vehiculos" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Asignacion_Vehiculos_Usuarios_id_usuario" FOREIGN KEY (id_usuario) REFERENCES "Usuarios" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Asignacion_Vehiculos_Vehiculos_id_vehiculo" FOREIGN KEY (id_vehiculo) REFERENCES "Vehiculos" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260803224443_migrations23') THEN
    CREATE TABLE "Asignacion_Pedidos" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        id_asignacion_vehiculo integer NOT NULL,
        id_pedido integer NOT NULL,
        "Fecha_Asignacion" timestamp with time zone NOT NULL,
        "Fecha_Entrega" timestamp with time zone NOT NULL,
        "Estado" text NOT NULL,
        CONSTRAINT "PK_Asignacion_Pedidos" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Asignacion_Pedidos_Asignacion_Vehiculos_id_asignacion_vehic~" FOREIGN KEY (id_asignacion_vehiculo) REFERENCES "Asignacion_Vehiculos" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Asignacion_Pedidos_Pedidos_id_pedido" FOREIGN KEY (id_pedido) REFERENCES "Pedidos" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260803224443_migrations23') THEN
    CREATE INDEX "IX_Asignacion_Pedidos_id_asignacion_vehiculo" ON "Asignacion_Pedidos" (id_asignacion_vehiculo);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260803224443_migrations23') THEN
    CREATE INDEX "IX_Asignacion_Pedidos_id_pedido" ON "Asignacion_Pedidos" (id_pedido);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260803224443_migrations23') THEN
    CREATE INDEX "IX_Asignacion_Vehiculos_id_usuario" ON "Asignacion_Vehiculos" (id_usuario);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260803224443_migrations23') THEN
    CREATE INDEX "IX_Asignacion_Vehiculos_id_vehiculo" ON "Asignacion_Vehiculos" (id_vehiculo);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260803224443_migrations23') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260803224443_migrations23', '9.0.18');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260812121404_AsignacionPedidoFechaEntregaNullable') THEN
    ALTER TABLE "Asignacion_Pedidos" ALTER COLUMN "Fecha_Entrega" DROP NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260812121404_AsignacionPedidoFechaEntregaNullable') THEN
    ALTER TABLE "Asignacion_Pedidos" ALTER COLUMN "Estado" TYPE character varying(30);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260812121404_AsignacionPedidoFechaEntregaNullable') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260812121404_AsignacionPedidoFechaEntregaNullable', '9.0.18');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260812210311_CrearAsignacionPedidoUsuario') THEN
    CREATE TABLE "Asignacion_Pedido_Usuarios" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Id_asignacion_pedido" integer NOT NULL,
        "Id_asignacion_vehiculo" integer NOT NULL,
        "Fecha" timestamp with time zone NOT NULL,
        "Estado" text NOT NULL,
        CONSTRAINT "PK_Asignacion_Pedido_Usuarios" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Asignacion_Pedido_Usuarios_Asignacion_Pedidos_Id_asignacion~" FOREIGN KEY ("Id_asignacion_pedido") REFERENCES "Asignacion_Pedidos" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Asignacion_Pedido_Usuarios_Asignacion_Vehiculos_Id_asignaci~" FOREIGN KEY ("Id_asignacion_vehiculo") REFERENCES "Asignacion_Vehiculos" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260812210311_CrearAsignacionPedidoUsuario') THEN
    CREATE INDEX "IX_Asignacion_Pedido_Usuarios_Id_asignacion_pedido" ON "Asignacion_Pedido_Usuarios" ("Id_asignacion_pedido");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260812210311_CrearAsignacionPedidoUsuario') THEN
    CREATE INDEX "IX_Asignacion_Pedido_Usuarios_Id_asignacion_vehiculo" ON "Asignacion_Pedido_Usuarios" ("Id_asignacion_vehiculo");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260812210311_CrearAsignacionPedidoUsuario') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260812210311_CrearAsignacionPedidoUsuario', '9.0.18');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260812211940_HistorialPersonalPedido') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260812211940_HistorialPersonalPedido', '9.0.18');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260817151853_CrearCierreCaja') THEN
    CREATE TABLE "Cierre_Cajas" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Id_usuario" integer NOT NULL,
        "Fecha_Apertura" timestamp with time zone NOT NULL,
        "Fecha_Cierre" timestamp with time zone,
        "Total_Efectivo" numeric(10,2) NOT NULL,
        "Total_QR" numeric(10,2) NOT NULL,
        "Total_Recaudado" numeric(10,2) NOT NULL,
        "Estado" character varying(30) NOT NULL,
        "Observacion" character varying(500),
        CONSTRAINT "PK_Cierre_Cajas" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Cierre_Cajas_Usuarios_Id_usuario" FOREIGN KEY ("Id_usuario") REFERENCES "Usuarios" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260817151853_CrearCierreCaja') THEN
    CREATE TABLE "Cierre_Caja_Detalles" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Id_cierre_caja" integer NOT NULL,
        "Id_pago" integer NOT NULL,
        "Fecha" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Cierre_Caja_Detalles" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Cierre_Caja_Detalles_Cierre_Cajas_Id_cierre_caja" FOREIGN KEY ("Id_cierre_caja") REFERENCES "Cierre_Cajas" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Cierre_Caja_Detalles_Pagos_Id_pago" FOREIGN KEY ("Id_pago") REFERENCES "Pagos" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260817151853_CrearCierreCaja') THEN
    CREATE INDEX "IX_Cierre_Caja_Detalles_Id_cierre_caja" ON "Cierre_Caja_Detalles" ("Id_cierre_caja");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260817151853_CrearCierreCaja') THEN
    CREATE INDEX "IX_Cierre_Caja_Detalles_Id_pago" ON "Cierre_Caja_Detalles" ("Id_pago");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260817151853_CrearCierreCaja') THEN
    CREATE INDEX "IX_Cierre_Cajas_Id_usuario" ON "Cierre_Cajas" ("Id_usuario");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260817151853_CrearCierreCaja') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260817151853_CrearCierreCaja', '9.0.18');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260822222804_AgregarImagenAProducto') THEN
    ALTER TABLE "Productos" ADD "Imagen" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260822222804_AgregarImagenAProducto') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260822222804_AgregarImagenAProducto', '9.0.18');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260828190200_AgregarMotivoEdicionAPedido') THEN
    ALTER TABLE "Pedidos" ADD "Motivo_Edicion" character varying(500);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260828190200_AgregarMotivoEdicionAPedido') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260828190200_AgregarMotivoEdicionAPedido', '9.0.18');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260828200203_AgregarDevolucionAPedido') THEN
    ALTER TABLE "Pedidos" ADD "Fecha_Devolucion" timestamp with time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260828200203_AgregarDevolucionAPedido') THEN
    ALTER TABLE "Pedidos" ADD "Motivo_Devolucion" character varying(500);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260828200203_AgregarDevolucionAPedido') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260828200203_AgregarDevolucionAPedido', '9.0.18');
    END IF;
END $EF$;
COMMIT;


-- =======================================================
-- DATOS INICIALES SEMILLA (ROLES Y TIPOS DE PAGO)
-- =======================================================
INSERT INTO ""Rols"" (""Id"", ""Descripcion"", ""Estado"") 
OVERRIDING SYSTEM VALUE
VALUES 
    (1, 'Administrador', 'Activo'),
    (2, 'Distribuidor', 'Activo'),
    (3, 'Cliente', 'Activo')
ON CONFLICT (""Id"") DO NOTHING;

SELECT setval(pg_get_serial_sequence('""Rols""', 'Id'), COALESCE(MAX(""Id""), 1)) FROM ""Rols"";

INSERT INTO ""Tipo_Pagos"" (""Id"", ""Descripcion"", ""Estado"") 
OVERRIDING SYSTEM VALUE
VALUES 
    (1, 'Efectivo', 'Activo'),
    (2, 'QR', 'Activo')
ON CONFLICT (""Id"") DO NOTHING;

SELECT setval(pg_get_serial_sequence('""Tipo_Pagos""', 'Id'), COALESCE(MAX(""Id""), 1)) FROM ""Tipo_Pagos"";
