// <auto-generated />
using System;
using BadyBackend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BadyBackend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260913032333_FixPendingModelChanges")]
    partial class FixPendingModelChanges
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BadyBackend.Models.Asignacion_Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("Fecha_Asignacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("Fecha_Entrega")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("id_asignacion_vehiculo")
                        .HasColumnType("integer");

                    b.Property<int>("id_pedido")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("id_asignacion_vehiculo");

                    b.HasIndex("id_pedido");

                    b.ToTable("Asignacion_Pedidos");
                });

            modelBuilder.Entity("BadyBackend.Models.Asignacion_Pedido_Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Id_asignacion_pedido")
                        .HasColumnType("integer");

                    b.Property<int>("Id_asignacion_vehiculo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Id_asignacion_pedido");

                    b.HasIndex("Id_asignacion_vehiculo");

                    b.ToTable("Asignacion_Pedido_Usuarios");
                });

            modelBuilder.Entity("BadyBackend.Models.Asignacion_Vehiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("id_usuario")
                        .HasColumnType("integer");

                    b.Property<int>("id_vehiculo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("id_usuario");

                    b.HasIndex("id_vehiculo");

                    b.ToTable("Asignacion_Vehiculos");
                });

            modelBuilder.Entity("BadyBackend.Models.Cierre_Caja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("Fecha_Apertura")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("Fecha_Cierre")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Id_usuario")
                        .HasColumnType("integer");

                    b.Property<string>("Observacion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal>("Total_Efectivo")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("Total_QR")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("Total_Recaudado")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("Id_usuario");

                    b.ToTable("Cierre_Cajas");
                });

            modelBuilder.Entity("BadyBackend.Models.Cierre_Caja_Detalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Id_cierre_caja")
                        .HasColumnType("integer");

                    b.Property<int>("Id_pago")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Id_cierre_caja");

                    b.HasIndex("Id_pago");

                    b.ToTable("Cierre_Caja_Detalles");
                });

            modelBuilder.Entity("BadyBackend.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Contraseña")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("BadyBackend.Models.Detalle_Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Id_pedido")
                        .HasColumnType("integer");

                    b.Property<int>("Id_producto")
                        .HasColumnType("integer");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("Id_pedido");

                    b.HasIndex("Id_producto");

                    b.ToTable("Detalle_Pedidos");
                });

            modelBuilder.Entity("BadyBackend.Models.Pago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Id_pedido")
                        .HasColumnType("integer");

                    b.Property<int>("Id_tipoPago")
                        .HasColumnType("integer");

                    b.Property<int>("Id_usuario")
                        .HasColumnType("integer");

                    b.Property<decimal>("MontoPagado")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("SaldoPendiente")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("Id_pedido");

                    b.HasIndex("Id_tipoPago");

                    b.HasIndex("Id_usuario");

                    b.ToTable("Pagos");
                });

            modelBuilder.Entity("BadyBackend.Models.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("Fecha_Devolucion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Id_cliente")
                        .HasColumnType("integer");

                    b.Property<int>("Id_sucursal")
                        .HasColumnType("integer");

                    b.Property<string>("Motivo_Devolucion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Motivo_Edicion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Observacion")
                        .HasColumnType("text");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("Id_cliente");

                    b.HasIndex("Id_sucursal");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("BadyBackend.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Imagen")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Precio")
                        .HasColumnType("numeric");

                    b.Property<int>("Stock")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("BadyBackend.Models.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Rols");
                });

            modelBuilder.Entity("BadyBackend.Models.Sucursal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Id_cliente")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Id_cliente");

                    b.ToTable("Sucursales");
                });

            modelBuilder.Entity("BadyBackend.Models.Tipo_Pago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tipo_Pagos");
                });

            modelBuilder.Entity("BadyBackend.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Contraseña")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("BadyBackend.Models.Usuario_rol", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("id_rol")
                        .HasColumnType("integer");

                    b.Property<int>("id_usuario")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("id_rol");

                    b.HasIndex("id_usuario");

                    b.ToTable("Usuario_Rols");
                });

            modelBuilder.Entity("BadyBackend.Models.Vehiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cantidad_Carga")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Placa")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Vehiculos");
                });

            modelBuilder.Entity("BadyBackend.Models.Asignacion_Pedido", b =>
                {
                    b.HasOne("BadyBackend.Models.Asignacion_Vehiculo", "Asignacion_vehiculo")
                        .WithMany("Asignacion_Pedidos")
                        .HasForeignKey("id_asignacion_vehiculo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BadyBackend.Models.Pedido", "Pedido")
                        .WithMany()
                        .HasForeignKey("id_pedido")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asignacion_vehiculo");

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("BadyBackend.Models.Asignacion_Pedido_Usuario", b =>
                {
                    b.HasOne("BadyBackend.Models.Asignacion_Pedido", "AsignacionPedido")
                        .WithMany("Asignacion_Pedido_Usuarios")
                        .HasForeignKey("Id_asignacion_pedido")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BadyBackend.Models.Asignacion_Vehiculo", "AsignacionVehiculo")
                        .WithMany("Asignacion_Pedido_Usuarios")
                        .HasForeignKey("Id_asignacion_vehiculo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AsignacionPedido");

                    b.Navigation("AsignacionVehiculo");
                });

            modelBuilder.Entity("BadyBackend.Models.Asignacion_Vehiculo", b =>
                {
                    b.HasOne("BadyBackend.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("id_usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BadyBackend.Models.Vehiculo", "Vehiculo")
                        .WithMany("Asignacion_Vehiculos")
                        .HasForeignKey("id_vehiculo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("BadyBackend.Models.Cierre_Caja", b =>
                {
                    b.HasOne("BadyBackend.Models.Usuario", "Usuario")
                        .WithMany("Cierre_Cajas")
                        .HasForeignKey("Id_usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("BadyBackend.Models.Cierre_Caja_Detalle", b =>
                {
                    b.HasOne("BadyBackend.Models.Cierre_Caja", "Cierre_Caja")
                        .WithMany("Cierre_Caja_Detalles")
                        .HasForeignKey("Id_cierre_caja")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BadyBackend.Models.Pago", "Pago")
                        .WithMany("Cierre_Caja_Detalles")
                        .HasForeignKey("Id_pago")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cierre_Caja");

                    b.Navigation("Pago");
                });

            modelBuilder.Entity("BadyBackend.Models.Detalle_Pedido", b =>
                {
                    b.HasOne("BadyBackend.Models.Pedido", "Pedido")
                        .WithMany("Detalle_Pedidos")
                        .HasForeignKey("Id_pedido")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BadyBackend.Models.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("Id_producto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("BadyBackend.Models.Pago", b =>
                {
                    b.HasOne("BadyBackend.Models.Pedido", "Pedido")
                        .WithMany("Pagos")
                        .HasForeignKey("Id_pedido")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BadyBackend.Models.Tipo_Pago", "TipoPago")
                        .WithMany("Pagos")
                        .HasForeignKey("Id_tipoPago")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BadyBackend.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("Id_usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("TipoPago");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("BadyBackend.Models.Pedido", b =>
                {
                    b.HasOne("BadyBackend.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("Id_cliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BadyBackend.Models.Sucursal", "Sucursal")
                        .WithMany()
                        .HasForeignKey("Id_sucursal")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Sucursal");
                });

            modelBuilder.Entity("BadyBackend.Models.Sucursal", b =>
                {
                    b.HasOne("BadyBackend.Models.Cliente", "Cliente")
                        .WithMany("Sucursales")
                        .HasForeignKey("Id_cliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("BadyBackend.Models.Usuario_rol", b =>
                {
                    b.HasOne("BadyBackend.Models.Rol", "Rol")
                        .WithMany("Usuario_Rols")
                        .HasForeignKey("id_rol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BadyBackend.Models.Usuario", "Usuario")
                        .WithMany("Usuario_Rols")
                        .HasForeignKey("id_usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("BadyBackend.Models.Asignacion_Pedido", b =>
                {
                    b.Navigation("Asignacion_Pedido_Usuarios");
                });

            modelBuilder.Entity("BadyBackend.Models.Asignacion_Vehiculo", b =>
                {
                    b.Navigation("Asignacion_Pedido_Usuarios");

                    b.Navigation("Asignacion_Pedidos");
                });

            modelBuilder.Entity("BadyBackend.Models.Cierre_Caja", b =>
                {
                    b.Navigation("Cierre_Caja_Detalles");
                });

            modelBuilder.Entity("BadyBackend.Models.Cliente", b =>
                {
                    b.Navigation("Sucursales");
                });

            modelBuilder.Entity("BadyBackend.Models.Pago", b =>
                {
                    b.Navigation("Cierre_Caja_Detalles");
                });

            modelBuilder.Entity("BadyBackend.Models.Pedido", b =>
                {
                    b.Navigation("Detalle_Pedidos");

                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("BadyBackend.Models.Rol", b =>
                {
                    b.Navigation("Usuario_Rols");
                });

            modelBuilder.Entity("BadyBackend.Models.Tipo_Pago", b =>
                {
                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("BadyBackend.Models.Usuario", b =>
                {
                    b.Navigation("Cierre_Cajas");

                    b.Navigation("Usuario_Rols");
                });

            modelBuilder.Entity("BadyBackend.Models.Vehiculo", b =>
                {
                    b.Navigation("Asignacion_Vehiculos");
                });
#pragma warning restore 612, 618
        }
    }
}
